import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import { Krona_One } from "next/font/google";
import "./globals.css";

const inter1 = Roboto({ subsets: ["latin"], weight: '400' }); 
const inter2 = Krona_One({ subsets: ["latin"], weight: '400' }); 


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter1.className}>{children}</body>
    </html>
  );

}
